app = "panda_arm"
version = "1.0"

[lowlevelcon]
env = "dev"
    [lowlevelcon.pid]
        pgain = 100.0
        igain = 0.0
        dgain = 0.0
    [lowlevelcon.pid2]
        type = "pg"
        host = "localhost"
        port = 5432

[master]
account = "admin"
password = "admin"